config/routes.rb
Dallascharts::Application.routes.draw do

    match 'd3_charts/sunburst_help_1.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/sunburst_help_1.png")
    match 'd3_charts/sunburst_help_2.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/sunburst_help_2.png")
    match 'd3_charts/sunburst_help_3.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/sunburst_help_3.png")
    match 'd3_charts/sunburst_help_4.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/sunburst_help_4.png")
    match 'd3_charts/bar_help_1.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/bar_help_1.png")
    match 'd3_charts/bar_help_2.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/bar_help_2.png")
    match 'd3_charts/bar_help_3.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/bar_help_3.png")
    match '/heatmap_help_1.png', :to => redirect("#{ActionController::Base.relative_url_root}/assets/heatmap_help_1.png")
    resources :d3_charts
    resources :geo_heat_maps

    match 'chartform' => 'd3_charts#chartform'
    match 'buildchart' => 'd3_charts#buildchart'
    match 'heatmapform' => 'geo_heat_maps#heatmapform'
    match 'buildheatmap' => 'geo_heat_maps#buildheatmap'

end

app/controllers/d3_charts_controller.rb
class D3ChartsController < ApplicationController

  include D3ChartsHelper
  # GET /d3_charts
  # GET /d3_charts.json
  def index
    #render :layout => 'zerb'    
    #
    # Probably not doing this the "Rails Way"
    #
    redirect_to chartform_url

    #build_chart_variables

    #@json_data = "some data"
    #finalhash = build_data_hierarch_hash_for_d3 PoliceReport, field_array, options_hash
  end

  # GET /d3_charts/1
  # GET /d3_charts/1.json
  def show
    build_chart_variables
    @chart_type = params[:id]
    render :layout => 'zerb_chartresults'    
  end

  def chartform
    @page_title = "Chart Builder"
    @avl_fields = [["Type Of Incident", :typeofincident],
                    ["Block", :block],
                    ["Street", :street],
                    ["Street And Block", :blockandstreet],
                    ["Date Of Call", :dateofincident],                    
                    ["Month", :monthname],
                    ["Week Of Year", :weekofyearstring],
                    ["Day of Week", :dayofweek],
                    ["Year", :yearnum]]    

    @avl_calltypes = [
                        ["Accidental Injury - Public Property", "AcInj_PP".capitalize],
                        ["Animal Bites", "AnmlBite".capitalize],
                        ["Arson AND Attempted Arson", "Arson".capitalize],
                        ["Auto Theft-UUMV", "AutoTheft".capitalize],
                        ["Burglary", "Burglary".capitalize],
                        ["Criminal Mischief/Valdalism", "Dist/Miscf.".capitalize],
                        ["CWP CH To Weapon", "CwpChToWeap".capitalize],
                        ["Disorderly Conduct", "Disord".capitalize],
                        ["Embezzlement", "Embez".capitalize],
                        ["Firearms Accidents", "FirearmAcc".capitalize],
                        ["Forgery & Counterfeiting", "Forgery".capitalize],
                        ["Found Property", "FoundProp".capitalize],
                        ["Fraud", "Fraud".capitalize],
                        ["Home Accidents", "HomeAcc".capitalize],
                        ["Lost Property", "LostProp".capitalize],
                        ["Robbery", "Robbery".capitalize],
                        ["Sudden Death-Bodies Found", "SudDeath/BodyFound".capitalize],
                        ["Theft", "Theft".capitalize],
                        ["Traffic Motor Vehicle", "TrafMotVeh".capitalize],
                     ]

    @avl_charts = [["Sunburst", :sunburst],
                   ["Bar", :hierchbar]] #,
                   #["Tree", :iztreegraph]]

    @chart_sizes = [['500 Low Resolution (Tablet/Phone)', 500],
                    ['700 Medium Resolution (Tablet/Phone)', 700],
                    ['900 High Resolution (Desktop)', 900],
                    ['1100 - Very High Resolution (Desktop)', 1100]]

    # this needs to go last
    #render :layout => 'multiselect'
    #render :layout => 'multiselect6One3'    
    render :layout => 'zerb'    

  end

  def buildchart
    # ok, we have been called by the chart builder, we need to take the inputs and convert it to
    # something that we can use
    chartparams = params[:buildchart] # because I'm lazy
    @baseurl = d3_charts_url

    @charttype = chartparams[:chart_type]    

    if @charttype.nil? || @charttype.size <= 0
      return redirect_to chartform_url, :flash => { :error => 'You Must Supply a Chart Type' }
    end

    #
    # TODO: PDB - comon, you can get rid of this double iteration
    #
    field_list = []
    @outgoing_url_params = []
    chartparams[:db_fields].each {|field|
      if field.size > 0
        field_list << field
      end
    }

    incident_type_list = []
    chartparams[:incident_types].each {|field|
      if field.size > 0
        incident_type_list << field
      end
    }


    if field_list.count <= 0
      return redirect_to chartform_url, :flash => { :error => 'You Must Select Fields for the report' }
    end

    # we may or may not have anything for the minimum count
    min_count = chartparams[:min_count]
    if !min_count.nil? && min_count.size > 0
      if min_count.to_i <= 0
        return redirect_to chartform_url, :flash => { :error => 'Minimum Count must be blank or integer > 0'}
      else
        @outgoing_url_params << "options[#{field_list[0]}][mincount]=#{min_count.to_i}"
      end
    end

    # see if we have a size parm
    if (chartparams.has_key? :chart_size) && (chartparams[:chart_size].to_i > 0)
      @outgoing_url_params << "options[global][width]=#{chartparams[:chart_size].to_i}"
      @outgoing_url_params << "options[global][height]=#{chartparams[:chart_size].to_i}"
    end

    # see if we have a title
    if chartparams.has_key? :chart_title
      @outgoing_url_params << "options[global][chart_title]=#{chartparams[:chart_title]}"      
    end

    if chartparams[:start_date]
      @outgoing_url_params << "options[global][start_date]=#{chartparams[:start_date]}"      
    else
      return redirect_to chartform_url, :flash => { :error => 'You Must Provide Start Date in Format mm-dd-yyyy' }
    end

    if chartparams[:end_date]
      @outgoing_url_params << "options[global][end_date]=#{chartparams[:end_date]}"
    else
      return redirect_to chartform_url, :flash => { :error => 'You Must Provide End Date in Format mm-dd-yyyy' }
    end

    # now that we have valid fields
    #   build up the field part of the url

    # ok, let's start picking this apart
    field_list.each_with_index { |value, index|
      # add the list to the fields to use, in the order the user had
      @outgoing_url_params << "fields[#{index}]=#{value}"

      # if a field is being listed, we are going to assume the user doesn't want blank values
      @outgoing_url_params << "options[#{value}][allow_blank]=false"
    }

    # if hierarch bar, no prepended counts, its the point of a bar graph
    if @charttype.to_s == "hierchbar"
      @outgoing_url_params << "options[global][noprependcount]"
    end

    # see if we are having to do a text search
    if chartparams[:text_search]&&chartparams[:text_search].strip.length > 0
      @outgoing_url_params << "options[global][text_search]=#{chartparams[:text_search]}"
    end

    include_string = "options[typeofincident][include]="
    incident_type_list.each { |value|
      # if a field is being listed, we are going to assume the user doesn't want blank values
      include_string << "#{value},"
    }
    include_string.chop!    
    @outgoing_url_params.unshift(include_string)

    # ok, build up our string
    @outgoing_url = @baseurl + "/" + @charttype + "?"
    @outgoing_url_params.each { |parameter|
      @outgoing_url << parameter
      @outgoing_url << "&"
    }
    @outgoing_url.chop!

    redirect_to @outgoing_url
  end

  # PDB TODO: This is really doing more than building_varibles. Rename
  def build_chart_variables
      # PDBPDB TODO: Need to reduce duplication
    calltype_rlookup = {  
      "Dist/Miscf.".downcase => "Criminal Mischief/Valdalism",
      "AnmlBite".downcase => "Animal Bites",
      "Theft".downcase => "Theft",
      "AutoTheft".downcase => "Auto Theft-UUMV",
      "AcInj_PP".downcase => "Accidental Injury - Public Property",
      "Arson".downcase => "Arson AND Attempted Arson",
      "Burglary".downcase => "Burglary",
      "Disord".downcase => "Disorderly Conduct",
      "Embez".downcase => "Embezzlement",
      "FirearmAcc".downcase => "Firearms Accidents",
      "Forgery".downcase => "Forgery & Counterfeitig",
      "FoundProp".downcase => "Found Property",
      "Fraud".downcase => "Fraud",
      "HomeAcc".downcase => "Home Accidents",
      "LostProp".downcase => "Lost Property",
      "Robbery".downcase => "Robbery",
      "SudDeath/BodyFound".downcase => "Sudden Death-Bodies Found",
      "TrafMotVeh".downcase => "Traffic Motor Vehicle",
      "CwpChToWeap".downcase => "CWP CH To Weapon",
    }
  
    # first, get the fields for the display
    @field_array = []
    params[:fields].keys.map {|x| x.to_i}.sort.each { |sorted_index|
      @field_array << params[:fields][sorted_index.to_s].to_sym 
    }

    @options_hash = params[:options]
    @options_hash = {} if @options_hash.nil?

    # convert string keys and nested string keys into symbols
    #PDB TODO: Comon pressly, move to the common call!!!!
    @options_hash = @options_hash.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}
    new_options_hash = {}
    # make sure mincount is integer
    @options_hash.each {|key, value|
      new_options_hash[key] = value.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}
      new_options_hash[key][:mincount] = new_options_hash[key][:mincount].to_i if new_options_hash[key].has_key? :mincount
      new_options_hash[key][:allow_blank] = new_options_hash[key][:allow_blank].downcase != "false" if new_options_hash[key].has_key? :allow_blank

      if new_options_hash[key].has_key? :include
        new_options_hash[key][:include] = new_options_hash[key][:include].split(",")
      end      

      if new_options_hash[key].has_key? :exclude
        new_options_hash[key][:exclude] = new_options_hash[key][:exclude].split(",")
      end      
    }
    
    @options_hash = new_options_hash

    # PDB TODO: Make customizable chart size defaults for each chart type
    @chart_height = 800
    if (@options_hash.has_key? :global) && (@options_hash[:global].has_key? :height)
      @chart_height = @options_hash[:global][:height].to_i
    end

    @chart_width = 800
    if (@options_hash.has_key? :global) && (@options_hash[:global].has_key? :width)
      @chart_width = @options_hash[:global][:width].to_i
    end

    # chart title
    @chart_title = ""
    if (@options_hash.has_key? :global) && (@options_hash[:global].has_key? :chart_title)
      @chart_title = @options_hash[:global][:chart_title]
    end

    @json_data = generate_d3_json PoliceReport, @field_array, @options_hash

    #
    # Ok, let's build some string data about what generated here
    #

app/helpers/d3_charts_helper.rb
module D3ChartsHelper
	#
	# This method does all the big work
	#  it takes the lists of fields to includes and options
	#
	def build_data_hierarch_hash_for_d3 active_record_class, field_list, options
	  myhash = {:name => "", :children => {}}

	  temprec = active_record_class
	  # for each database object
    # see if we can build in date comparisons
    if options[:global][:start_date]
      temprec = temprec.where("dateofincident >= ?", options[:global][:start_date])
    end

    if options[:global][:end_date]
      temprec = temprec.where("dateofincident <= ?", options[:global][:end_date])
    end

    if options[:typeofincident][:include]          
      temprec = temprec.where(:typeofincident => options[:typeofincident][:include])
    end

	  # active_record_class.all.each { |x|
    temprec.all.each { |x|

	    # if this one got filtered, skip it
	    next if is_filtered? x, options

	    temphash = myhash
	    toplevelhash = myhash
	    index = 0
	    # Run through all the specified fields for each database record
	    while index < field_list.count
	      field = field_list[index] # get the field name
	      field_value = x[field] # get the field value

	      # see if field is blank and if we need to block it (because allow_block turned off in options)
	      if field_value.nil? || ((field_value.respond_to? :empty) && (field_value.empty?))
	        if (options.has_key? field) && (options[field].has_key? :allow_blank) && (!options[field][:allow_blank])
	          break # break out of while, we are done
	        end
	      end

	      # we have to treat the last field data special (the bottom of hierarcy is different)
	        bottom_level = index == field_list.count - 1

	        # if you don't already have a child element for this field, add it
	        if !temphash[:children].has_key? field_value
	          temphash[:children][field_value] = {:name => field_value.to_s, :field => field, :size => 0}
	          # need to add child hash if not bottom levl
	          temphash[:children][field_value][:children] = {} if !bottom_level
	        end

	        # always bump the count for this child level
	        temphash[:children][field_value][:size] += 1
	        if index != field_list.count - 1
	          # we are not at bottom of hierarchy, add children hash
	          #temphash[:children][field_value][:children] = {}
	          temphash = temphash[:children][field_value] if !bottom_level # point to next level of hierarch for next iter
	        end

	      index += 1
	    end
	  }

	  # now we have to convert the "children hashes to arrays, yuck"
	  # needed the children stored in a hash for efficient access. However,
	  #   the D3 library wants a child collection (array), so I have to convert
	  children_hash_to_array_with_min_filtering myhash, options
	end

	#
	# == this method convers the children hashes we like to the children
	#   array that D3 expects.
	#
	#  Note that I muddled the water a bit by doing some size filtering
	#    It is more effiecient this way because we are already iterating
	#    through the structure
	#
	def children_hash_to_array_with_min_filtering(childrenhash, option_hash)
	  if childrenhash && childrenhash.class.to_s == "Hash"
	    if childrenhash.has_key? :children
	      # ok, if we get here, we acutally have a children hash to deal with
	      childrenhash[:children] = childrenhash[:children].values # get children hashes
	      goodchildren = [] # goodchildren have passed the size checks
	      childrenhash[:children].each {|x|
	        if x.has_key?(:size) && (!x[:name].nil?)
	          field_options = option_hash[x[:field]]
	          if !field_options.nil? && (field_options.has_key? :mincount)
	            if x[:size] >= field_options[:mincount]
	              goodchildren << x
	            end
	          else
	            goodchildren << x
	          end
	        
	        	unless (option_hash.has_key? :global) && (option_hash[:global].has_key? :noprependcount)
	          	x[:name] =  "(#{x[:size]}) " + x[:name]
	          end

	        end
	        # since each children hash can have children of its own, we 
	        #   have to recursively call down to bottom of hierarchy
	        children_hash_to_array_with_min_filtering x, option_hash 
	      }
	      childrenhash[:children] = goodchildren
	    else
	      childrenhash = childrenhash.values
	    end
	  end

	  childrenhash
	end

	def generate_d3_json active_record_class, field_array, options_hash
	  finalhash = build_data_hierarch_hash_for_d3 PoliceReport, field_array, options_hash
	  auto_trim_hash finalhash, options_hash
		finalhash.to_json.html_safe
		#JSON.pretty_generate(finalhash).html_safe
	end

	def auto_trim_hash results_hash, options_hash
		# PDB: TODO - You need to make this more refined before actually using
		return

		size_count_hash = {}
		results_hash[:children].each { |elem|
			if !size_count_hash.has_key? elem[:size]
					size_count_hash[elem[:size]] = 0
			end

			size_count_hash[elem[:size]] += 1			
		}

		new_arr = size_count_hash.sort_by {|value, count| value * -1}

		low = 20
		low_limit = 0
		high_limit = 0
		high = 30
		sum = 0
		new_arr.each { |subarr|
			if sum < 15 and (sum + subarr[1]) >= 15
				low_limit = subarr[0]
			end

			if sum < 25 and (sum + subarr[1]) >= 25
				high_limit = subarr[0]
			end

			sum += subarr[1]
		}

#		puts "%%%%%%% #{high_limit} -- #{low_limit} %%%%%%%"

		# PDB Another spin through! you got to be kidding me
		final_arr = []
		results_hash[:children].each { |elem|
			if elem[:size] >= low_limit
				final_arr << elem
			end
		}
		results_hash[:children] = final_arr

	end
end

app/views/d3_charts/_hierchbar.html.erb
<!-- This is all rendered inside the body tag -->
<!--
<script type="text/javascript">
  var log = log4javascript.getDefaultLogger();
</script>
-->

    <style type="text/css">
      svg {
        font-size: 14px;
      }

      rect.background {
        fill: none;
        pointer-events: all;
      }

      .axis {
        shape-rendering: crispEdges;
      }

      .axis path, .axis line {
        fill: none;
        stroke: #000;
        stroke-width: .5px;
      }
    </style>
    <script type="text/javascript">
      var m = [80, 200, 0, 200], // top right bottom left
          w = <%=@chart_width%> - m[1] - m[3], // width
          h = <%=@chart_height%> - m[0] - m[2], // height
          x = d3.scale.linear().range([0, w]),
          y = 25, // bar height
          z = d3.scale.ordinal().range(["steelblue", "#aaa"]); // bar color
      var root = <%= @json_data %>
    </script>

    <%= javascript_include_tag "hierchbar.min" %>

app/views/d3_charts/_sunburst.html.erb
<style>
  path {
    stroke: #fff;
    fill-rule: evenodd;
  }

  text {
    font-family: Arial, sans-serif;
    font-size: 12px;
  }

</style>

<script>
var width = <%=@chart_width%>,
    height = <%=@chart_height%>,
    radius = Math.min(width, height) / 2;
var jsonBlob = <%= @json_data %>

</script>
<%= javascript_include_tag "sunburst.min" %>

app/views/d3_charts/buildchart.html.erb
<h1>Hello World!!</h1>
<%= @baseurl %>
<br>
<%= @charttype %>
<br>
<%= @outgoing_url %>
<br>
<%= debug @outgoing_url_params %>

app/views/d3_charts/chartform.html.erb
<style type="text/css">
  #dbfieldselect  {
  }

</style>

<script type="text/javascript">
$(function () {
      $('#startdateinput').fdatepicker(); 
      $('#enddateinput').fdatepicker(); 
    });
  </script>

<script type="text/javascript">
  $(function(){
    $("#dbfieldselect").multiselect({ sortable: true, searchField: false });
    $("#incidenttypeselect").multiselect({ sortable: true, searchField: false });
  });

  </script>

<div id="content">

<div class="row"> <!-- outer row -->
<div class="large-8 columns">

  <div class="row">
    <div class="large-12 columns">
      <h1> Chart Generator - Dallas Law Enforcement Incidents </h1>
    </div>
  </div>

<%= simple_form_for :buildchart, { :url => buildchart_url } do |f| %>
  <div class="row">
    <div class="large-12 columns">
    <span data-tooltip class="has-tip" title="Enter title for your Chart (optional)">Title</span>
      <%= f.input :chart_title, :label => false, :required => false %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <span data-tooltip class="has-tip" title="Enter text search terms separated by commas. Terms can be any word(s) found in incident reports. Examples include: offense details, street name, etc.">Text Search</span>
      <%= f.input :text_search, :label => false, :required => false %>
    </div>
  </div>

  <!-- How to autoselect -->
  <div class="row">
    <div class="large-6 columns">
    <span data-tooltip class="has-tip" title="Select chart type to produce">Chart Type</span>
      <%= f.input :chart_type, :label => false, :collection => @avl_charts, :selected => :sunburst %>
      <div class="show-for-small">
        <br> <!-- PDB NOTE - hide-for-large no work, but show for small did-->
      </div>

    </div>
    <div class="large-6 columns">
    <span data-tooltip class="has-tip" title="Select chart size appropriate for your display device">Chart Size (width)</span>
      <%= f.input :chart_size, :collection => @chart_sizes, :label => false, :selected => 700  %>
    </div>
  </div>

  <div class="row">
    <br>
    <div class="large-6 columns">
    <span data-tooltip class="has-tip" title="Mouse-click or touch date below to show date chooser for Start Date">Start Date</span>
    <input type="text" data-date-format="mm/dd/yyyy" value="<%= 1.month.ago.strftime("%m/%d/%Y") %>" id="startdateinput" name="buildchart[start_date]" readonly>
    </div>
    <div class="large-6 columns">
    <span data-tooltip class="has-tip" title="Mouse-click or touch date below to show date chooser for End Date">End Date</span>
    <input type="text" data-date-format="mm/dd/yyyy" value="<%= 1.second.ago.strftime("%m/%d/%Y") %>" id="enddateinput" name="buildchart[end_date]" readonly>
    </div>
  </div>

  <div class="row">
    <div class="large-6 columns">
    <span data-tooltip class="has-tip" title="Minimum Number of Incidents Required for First Selection. Higher minimum numbers will result in less cluttered charts. This number only limits results for the first option listed in your selections below. Experiment with this value to get desired results.">Minimum Number of Incidents</span>
      <%= f.input :min_count, :label => false, :required => false, :input_html => {:maxlength => 7, :size => 7}%>
    </div>
    <div class="large-6 columns"></div>
  </div>
  <div class="row">
    <div class="large-12 columns">
    <div class="panel">
  Select the fields to include in chart. Fields on the left side are selected, fields on the right are not selected. Clicking or touching a field will toggle its selection status. Selected fields may be ordered via mouse or touch drag/drop. The ordering will determine the heirarchy represented in the reports.
    </div>
    </div>
  </div>

  <div class="row">
  <div class="small-9 small-non-centered large-9 large-centered columns">
    <%= f.select(:db_fields, @avl_fields,{},
                                       { :multiple => true, :size => 5, :class => "multiselect", :id => "dbfieldselect" }
                                     ) %>
  </div>
  </div>

  <div class="row"><br></div>

  <div class="row">
    <div class="large-12 columns">
    <div class="panel">
Select the incident types in the list below to include in the chart. Incident types on the left side will be included in the chart, and those on the right side will be excluded. Clicking or touching a field will move the field from one column to the other. <br><br><b>Field ordering is not important for incident types.</b>
    </div>
    </div>
  </div>


  <div class="row">
  <br>
  <div class="small-9 small-non-centered large-9 large-centered columns">
  <%= f.select(:incident_types, @avl_calltypes,{},
                                     { :multiple => true, :size => 5, :class => "multiselect", :id => "incidenttypeselect" }
                                   ) %>
    </div>
  <div class="large-3 columns"></div>
  </div>


  </div> <!-- outer columns -->
  <div class="large-4 columns hide-for-small">

    <center><h4><span data-tooltip class="has-tip" title="An interactive sunburst chart displays all the charted information at once. You can drill down or zoom in to the information by mouse clicking or touching on an area of interest. Zoom back out by mouse clicking or touching on the center circle.">Sunburst Chart</span></h4></center>
    <%= image_tag "6one3-charts_sunburst_ex.svg", :align => "center"  %>
    <hr>
      <center><h4><span data-tooltip class="has-tip" title="An interactive bar chart only shows the top level data (first selected option), but you can zoom in to data sub elements (second selected option and so forth) for each bar by clicking on it. Zoom out by clicking in the open white area around the bars.">Bar Chart</span></h4></center>
    <%= image_tag "6one3-charts_bar_ex.svg", :align => "center"  %>    
  </div>
  </div> <!-- Outer row -->


 <div class="row">
 <br>
 <br>
    <div class="small-10 small-centered large-10 large-centered columns">
      <br>
      <a data-reveal-id="disclaimerModal" href="#" class="radius button secondary">Disclaimer</a>      
      <a data-reveal-id="termsOfUseModal" href="#" class="radius button secondary">Terms Of Use</a>      
      <%= f.button :submit, "Generate Chart", :class => "medium button success radius" %>      
    </div>
  </div>
<% end %>

app/views/d3_charts/index.html.erb
<!--
<script type="text/javascript">
  var log = log4javascript.getDefaultLogger();
</script>
-->


<script type="text/javascript">
$(function () {
      $('#dp3').fdatepicker({
          closeButton: true
        }); 
      $('#dp1').fdatepicker({
          closeButton: true
        }); 

    });
  </script>

  <div class="row">
    <input type="text" class="small 3 columns" value="02-16-2012" id="dp1">
  </div>

  <div class="row date collapse" id="dp3" data-date="02-12-2012" data-date-format="mm-dd-yyyy">
    <input class="small-3 columns date collapse" size="16" type="text" value="02-12-2012" readonly> 
    <span class="prefix small-2 columns end"><i class="icon-calendar"></i></span>
  </div>

app/views/d3_charts/show.html.erb
<%= render @chart_type %>